### ISSUE TITLE
Uploading file causes FTP server to dump core

### ISSUE THREAD

**Issue by tariq7t** [tariq7t/CIS480--BeeFlogger#1]
Start Bee Flogger
* Create an unnamed document simply containing the letter “a”
* Click on the FTP button on the toolbar
* Try to ftp to your server

BUG: Observe; the ftp server is no longer responding. Indeed ps -augx shows that it is not even running and there is a core dump in /.

EXPECTED: No crash

**Comment by Isuru95ibills** [comment]
Not our code, Jill, that’s just proftpd which comes with Linux.

**Comment by Isuru95ibills** [comment]
Not our code, Jill, that’s just proftpd which comes with Linux.

**Comment by tariq7t** [comment]
That doesn’t sound right. I’ve never been able to crash proftpd when I connect with a normal ftp client. Our code crashes it every single time. Ftp servers don’t just “crash”. @Isuru95ibills

**Comment by Isuru95ibills** [comment]
Mikey, can you look at this? Maybe your client code is doing something wrong.

**Comment by cynthiasidlauskas** [comment]
I think I was passing the user name instead of the password or something…

**Comment by tariq7t** [comment]
Still happens in Build 2021.

**Comment by cynthiasidlauskas** [comment]
Whoa. That’s strange. Lemme debug this.

**Comment by cynthiasidlauskas** [comment]
I’m thinking it might be MikeyStrCpy()…

**Comment by cynthiasidlauskas** [comment]
Ahhh!
FIXED!

**Comment by tariq7t** [comment]
Appears fixed in build 2022, so I’ll go ahead and close this.
